export default {
  Organization: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid", example: "a306b07d-f92f-46c5-b8a8-5cad63d328b3" },
      name: { type: "string", example: "Default Organization" },
      slug: { type: "string", example: "default" },
      email: { type: "string", format: "email", example: "contact@example.com", nullable: true },
      phone: { type: "string", example: "+33 1 23 45 67 89", nullable: true },
      address: { type: "string", example: "123 Rue de la Mode", nullable: true },
      city: { type: "string", example: "Paris", nullable: true },
      postal_code: { type: "string", example: "75001", nullable: true },
      country: { type: "string", example: "France", nullable: true },
      logo_url: { type: "string", format: "uri", example: "https://example.com/logo.png", nullable: true },
      settings: { type: "object", nullable: true },
      subscription_plan: { type: "string", example: "pro" },
      subscription_status: { type: "string", example: "active" },
      trial_ends_at: { type: "string", format: "date-time", nullable: true },
      is_active: { type: "boolean", example: true },
      created_at: { type: "string", format: "date-time" },
      updated_at: { type: "string", format: "date-time" },
    },
  },
  OrganizationStats: {
    type: "object",
    properties: {
      users: { type: "integer", example: 5 },
      dresses: { type: "integer", example: 120 },
      customers: { type: "integer", example: 450 },
      prospects: { type: "integer", example: 23 },
      active_contracts: { type: "integer", example: 15 },
      rented_dresses: { type: "integer", example: 35, description: "Number of dresses currently rented in active contracts" },
    },
  },
  CreateOrganizationInput: {
    type: "object",
    required: ["name", "slug"],
    properties: {
      name: { type: "string", example: "New Boutique" },
      slug: { type: "string", example: "new-boutique" },
      email: { type: "string", format: "email", example: "contact@newboutique.com" },
      phone: { type: "string", example: "+33 1 23 45 67 89" },
      address: { type: "string", example: "456 Avenue des Champs" },
      city: { type: "string", example: "Lyon" },
      postal_code: { type: "string", example: "69001" },
      country: { type: "string", example: "France" },
      subscription_plan: { type: "string", example: "basic", enum: ["free", "basic", "pro", "enterprise"] },
    },
  },
  UpdateOrganizationInput: {
    type: "object",
    properties: {
      name: { type: "string", example: "Updated Organization Name" },
      email: { type: "string", format: "email", example: "newemail@example.com" },
      phone: { type: "string", example: "+33 1 23 45 67 89" },
      address: { type: "string", example: "New Address" },
      city: { type: "string", example: "Paris" },
      postal_code: { type: "string", example: "75001" },
      country: { type: "string", example: "France" },
      logo_url: { type: "string", format: "uri" },
      settings: { type: "object" },
    },
  },
};
